# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'parkinson3.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn import svm
from sklearn.metrics import accuracy_score

class Ui_parkinson3(object):
    def setupUi(self, parkinson3):
        parkinson3.setObjectName("parkinson3")
        parkinson3.resize(1075, 760)
        parkinson3.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        parkinson3.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.label = QtWidgets.QLabel(parkinson3)
        self.label.setGeometry(QtCore.QRect(370, 20, 100, 650))
        self.label.setStyleSheet("border-image: url(:/image/parkinson2.jpg);\n"
"border-top-left-radius:50px;\n"
"border-bottom-left-radius:50px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parkinson3)
        self.label_2.setGeometry(QtCore.QRect(920, 20, 100, 650))
        self.label_2.setStyleSheet("border-image: url(:/image/parkinson2.jpg);\n"
"border-top-right-radius:50px;\n"
"border-bottom-right-radius:50px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(parkinson3)
        self.label_4.setGeometry(QtCore.QRect(650, 30, 90, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:rgba(200,0,0,200)")
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(parkinson3)
        self.lineEdit.setGeometry(QtCore.QRect(520, 70, 150, 30))
        self.lineEdit.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(150,0,0,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(parkinson3)
        self.label_3.setGeometry(QtCore.QRect(470, 20, 450, 650))
        self.label_3.setStyleSheet("background-color:rgba(255,255,255,255);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(parkinson3)
        self.lineEdit_2.setGeometry(QtCore.QRect(520, 170, 150, 30))
        self.lineEdit_2.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(150,0,0,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(parkinson3)
        self.lineEdit_3.setGeometry(QtCore.QRect(520, 120, 150, 30))
        self.lineEdit_3.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(150,0,0,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(parkinson3)
        self.lineEdit_4.setGeometry(QtCore.QRect(520, 270, 150, 30))
        self.lineEdit_4.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(150,0,0,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(parkinson3)
        self.lineEdit_5.setGeometry(QtCore.QRect(520, 220, 150, 30))
        self.lineEdit_5.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(150,0,0,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(parkinson3)
        self.lineEdit_6.setGeometry(QtCore.QRect(520, 470, 150, 30))
        self.lineEdit_6.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(150,0,0,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(parkinson3)
        self.lineEdit_7.setGeometry(QtCore.QRect(520, 420, 150, 30))
        self.lineEdit_7.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(150,0,0,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(parkinson3)
        self.lineEdit_8.setGeometry(QtCore.QRect(520, 370, 150, 30))
        self.lineEdit_8.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(150,0,0,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(parkinson3)
        self.lineEdit_9.setGeometry(QtCore.QRect(520, 320, 150, 30))
        self.lineEdit_9.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(150,0,0,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(parkinson3)
        self.lineEdit_10.setGeometry(QtCore.QRect(520, 520, 150, 30))
        self.lineEdit_10.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(150,0,0,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_11 = QtWidgets.QLineEdit(parkinson3)
        self.lineEdit_11.setGeometry(QtCore.QRect(720, 70, 150, 30))
        self.lineEdit_11.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(150,0,0,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(parkinson3)
        self.lineEdit_12.setGeometry(QtCore.QRect(720, 120, 150, 30))
        self.lineEdit_12.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(150,0,0,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_13 = QtWidgets.QLineEdit(parkinson3)
        self.lineEdit_13.setGeometry(QtCore.QRect(720, 170, 150, 30))
        self.lineEdit_13.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(150,0,0,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_14 = QtWidgets.QLineEdit(parkinson3)
        self.lineEdit_14.setGeometry(QtCore.QRect(720, 220, 150, 30))
        self.lineEdit_14.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(150,0,0,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.lineEdit_15 = QtWidgets.QLineEdit(parkinson3)
        self.lineEdit_15.setGeometry(QtCore.QRect(720, 270, 150, 30))
        self.lineEdit_15.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(150,0,0,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.lineEdit_16 = QtWidgets.QLineEdit(parkinson3)
        self.lineEdit_16.setGeometry(QtCore.QRect(720, 320, 150, 30))
        self.lineEdit_16.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(150,0,0,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.lineEdit_17 = QtWidgets.QLineEdit(parkinson3)
        self.lineEdit_17.setGeometry(QtCore.QRect(720, 370, 150, 30))
        self.lineEdit_17.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(150,0,0,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.lineEdit_18 = QtWidgets.QLineEdit(parkinson3)
        self.lineEdit_18.setGeometry(QtCore.QRect(720, 420, 150, 30))
        self.lineEdit_18.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(150,0,0,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.lineEdit_19 = QtWidgets.QLineEdit(parkinson3)
        self.lineEdit_19.setGeometry(QtCore.QRect(720, 470, 150, 30))
        self.lineEdit_19.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(150,0,0,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.lineEdit_20 = QtWidgets.QLineEdit(parkinson3)
        self.lineEdit_20.setGeometry(QtCore.QRect(720, 520, 150, 30))
        self.lineEdit_20.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(150,0,0,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.pushButton = QtWidgets.QPushButton(parkinson3)
        self.pushButton.setGeometry(QtCore.QRect(650, 630, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color:rgba(200, 0, 0,200);\n"
"    border-radius:10px;\n"
"    color:rgb(255, 255, 255)\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(255, 72, 26)\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_21 = QtWidgets.QLineEdit(parkinson3)
        self.lineEdit_21.setGeometry(QtCore.QRect(720, 570, 150, 30))
        self.lineEdit_21.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(150,0,0,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.lineEdit_22 = QtWidgets.QLineEdit(parkinson3)
        self.lineEdit_22.setGeometry(QtCore.QRect(520, 570, 150, 30))
        self.lineEdit_22.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(150,0,0,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.lineEdit.raise_()
        self.lineEdit_3.raise_()
        self.lineEdit_2.raise_()
        self.lineEdit_5.raise_()
        self.lineEdit_4.raise_()
        self.lineEdit_9.raise_()
        self.lineEdit_8.raise_()
        self.lineEdit_7.raise_()
        self.lineEdit_6.raise_()
        self.lineEdit_10.raise_()
        self.lineEdit_22.raise_()
        self.pushButton.raise_()
        self.lineEdit_11.raise_()
        self.lineEdit_12.raise_()
        self.lineEdit_13.raise_()
        self.lineEdit_14.raise_()
        self.lineEdit_15.raise_()
        self.lineEdit_16.raise_()
        self.lineEdit_20.raise_()
        self.lineEdit_17.raise_()
        self.lineEdit_21.raise_()
        self.lineEdit_18.raise_()
        self.lineEdit_19.raise_()

        self.retranslateUi(parkinson3)
        QtCore.QMetaObject.connectSlotsByName(parkinson3)

    def retranslateUi(self, parkinson3):
        _translate = QtCore.QCoreApplication.translate
        parkinson3.setWindowTitle(_translate("parkinson3", "Form"))
        self.label_4.setText(_translate("parkinson3", "Parkinson "))
        self.lineEdit.setPlaceholderText(_translate("parkinson3", "MDVP:Fo(Hz)"))
        self.lineEdit_2.setPlaceholderText(_translate("parkinson3", "MDVP:Flo(Hz)"))
        self.lineEdit_3.setPlaceholderText(_translate("parkinson3", "MDVP:Fhi(Hz)"))
        self.lineEdit_4.setPlaceholderText(_translate("parkinson3", "MDVP:Jitter(Abs)"))
        self.lineEdit_5.setPlaceholderText(_translate("parkinson3", "MDVP:Jitter(%)"))
        self.lineEdit_6.setPlaceholderText(_translate("parkinson3", "MDVP:Shimmer"))
        self.lineEdit_7.setPlaceholderText(_translate("parkinson3", "Jitter:DDP"))
        self.lineEdit_8.setPlaceholderText(_translate("parkinson3", "MDVP:PPQ"))
        self.lineEdit_9.setPlaceholderText(_translate("parkinson3", "MDVP:RAP"))
        self.lineEdit_10.setPlaceholderText(_translate("parkinson3", "MDVP:Shimmer(dB)"))
        self.lineEdit_11.setPlaceholderText(_translate("parkinson3", "Shimmer:APQ3"))
        self.lineEdit_12.setPlaceholderText(_translate("parkinson3", "MDVP:APQ"))
        self.lineEdit_13.setPlaceholderText(_translate("parkinson3", "Shimmer:DDA"))
        self.lineEdit_14.setPlaceholderText(_translate("parkinson3", "NHR"))
        self.lineEdit_15.setPlaceholderText(_translate("parkinson3", "HNR"))
        self.lineEdit_16.setPlaceholderText(_translate("parkinson3", "RPDE"))
        self.lineEdit_17.setPlaceholderText(_translate("parkinson3", "DFA"))
        self.lineEdit_18.setPlaceholderText(_translate("parkinson3", "spread1"))
        self.lineEdit_19.setPlaceholderText(_translate("parkinson3", "spread2"))
        self.lineEdit_20.setPlaceholderText(_translate("parkinson3", "D2"))
        self.pushButton.setText(_translate("parkinson3", "Valider"))
        self.lineEdit_21.setPlaceholderText(_translate("parkinson3", "PPE"))
        self.lineEdit_22.setPlaceholderText(_translate("parkinson3", "Shimmer:APQ5"))

        self.pushButton.clicked.connect(self.verifier)
    
    def verifier(self):
            parkinson = pd.read_csv('parkinsons.csv')
            
            data = parkinson
            
            x = data.drop(columns = ['name','status'], axis=1)
            y = data['status']
            
            x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=2)
            
            scaler = StandardScaler()
            scaler.fit(x_train)
            
            x_train = scaler.transform(x_train)
            x_test = scaler.transform(x_test)
            
            model = svm.SVC()
            
            model.fit(x_train,y_train)
            

            x_train_prediction = model.predict(x_train)
            training_data_accuracy = accuracy_score(y_train,x_train_prediction)
            
            MDVP_FO = self.lineEdit.text()
            MDVP_FHI = self.lineEdit_3.text()
            MDVP_F0 = self.lineEdit_2.text()
            MDVP_JITTER_P = self.lineEdit_5.text()
            MDVP_JITTER_A = self.lineEdit_4.text()
            MDVP_RAP = self.lineEdit_9.text()
            MDVP_PPQ =self.lineEdit_8.text()
            JITTER_DDP = self.lineEdit_7.text()
            MDVP_SHIMMER = self.lineEdit_6.text()
            MDVP_SHIMMER_DB =self.lineEdit_10.text()
            SHIMMER_APQ5 = self.lineEdit_22.text()
            SHIMMER_APQ3 = self.lineEdit_11.text()
            MDVP_APQ = self.lineEdit_12.text()
            SHIMMER_DDA = self.lineEdit_13.text()
            NHR = self.lineEdit_14.text()
            HNR = self.lineEdit_15.text()
            RPDE = self.lineEdit_16.text()
            DFA = self.lineEdit_17.text()
            SPREAD_1 = self.lineEdit_18.text()
            SPREAD_2 = self.lineEdit_19.text()
            D2 = self.lineEdit_20.text()
            PPE = self.lineEdit_21.text()
            
            input_data = (MDVP_FO,MDVP_FHI,MDVP_F0,MDVP_JITTER_P,MDVP_JITTER_A,MDVP_RAP,MDVP_PPQ,JITTER_DDP,MDVP_SHIMMER,MDVP_SHIMMER_DB,SHIMMER_APQ5,SHIMMER_APQ3,MDVP_APQ,SHIMMER_DDA,NHR,HNR,RPDE, DFA, SPREAD_1, SPREAD_2,D2,PPE)

            input_data_as_numpy_array = np.asarray(input_data)
            
            input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)
            
            std_data = scaler.transform(input_data_reshaped)

            prediction = model.predict(std_data)
            print(prediction)
        
    
            if (prediction[0] == 0):
                print("yesss")
                dialog = QMessageBox(parkinson3)
                dialog.setText("la personne est atteinte du Parkinson")
                dialog.setWindowTitle("resultat")
                dialog.exec_()  
          
            else:
                dialog = QMessageBox(parkinson3)
                dialog.setText("la personne n est pas atteinte du Parkinson")
                dialog.setWindowTitle("resultat")
                dialog.exec_()  
          

import app_parkinson

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    parkinson3 = QtWidgets.QWidget()
    ui = Ui_parkinson3()
    ui.setupUi(parkinson3)
    parkinson3.show()
    sys.exit(app.exec_())
